apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  conf.toml: |
    "DbUser" = "postgres"
    "DbPassword" = "{{ .Values.postgresql.postgresqlPassword }}"
    "DbName" = "postgres"
    "DbPort" = "5432"
    "DbHost" = "servian-postgresql"
    "ListenHost" = "0.0.0.0"
    "ListenPort" = "3000"   
   
